### ISSUE TITLE
Iris/Shaders incompatibility

### ISSUE THREAD

**Issue by Paneled** [SteamworkMC/Seaborgium#2]
Hey, not here to bother you, but this mod is incompatible with shaders(Iris Mod). I am not sure if this is a planned fix, however you should list this Iris as incompatible.

**Comment by UndefinedBHVR** [comment]
I'll go ahead and work on a compatibility patch. Thank you for letting me know.

**Comment by UndefinedBHVR** [comment]
The issue should be resolved with version 0.1.1 on Modrinth @Paneled please let me know if it worked.

**Comment by Paneled** [comment]
Hey, unfortunately this didn't fix the issue and is still giving 
`[13:21:53] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Wrong component type or count.'` 
`[13:21:53] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. The operation is invalid when the uniform is a matrix.'`
While the entire screen turns into one color

**Comment by UndefinedBHVR** [comment]
Can you provide me the name of the shader causing this? I was unable to replicate it with Complimentary.

**Comment by UndefinedBHVR** [comment]
Update: I just realized the issue. The function I was using to tell it to reload doesn't get called when shaders are loaded through the menu. Fixing now.

**Comment by UndefinedBHVR** [comment]
Should be resolved once I add 0.1.2 to Modrinth

**Comment by UndefinedBHVR** [comment]
Fixed with release [#0.1.2](https://modrinth.com/mod/seaborgium/version/0.1.2)

**Comment by ghost** [comment]
Excuse me, Iris Shaders now works with 0.1.2 but rendering issues happen whenever I change dimensions.
Reloading/Toggling shaders fixes it.

https://user-images.githubusercontent.com/52627381/235540719-9236946b-fa30-49c9-a381-0608e7ff97d5.mp4

The log also spammed similar things to what [Paneled](https://github.com/Paneled) mentioned too.
[latest.log](https://github.com/SteamworkMC/Seaborgium/files/11368393/latest.log)

**Comment by UndefinedBHVR** [comment]
I think I might know what's happening here. I'll go ahead and try to resolve it.

**Comment by UndefinedBHVR** [comment]
Should be resolved with the new version of 0.1.3, let me know.

**Comment by ghost** [comment]
I can confirm that it's now fixed.



https://user-images.githubusercontent.com/52627381/235820520-e15955a0-d2f7-4558-9111-8a4c5b228414.mp4

**Comment by UndefinedBHVR** [comment]
Thank you! Closing now.

**Comment by prdac123** [comment]
Hey so it turns out this isn't fixed. I don't know if its a direct incompatibility between seaborgium and iris or some other mod I'm using (don't have the time to test though), but reloading shaders (or changing dimensions, changing settings, or anything that causes some rendering part of the game to reload (like physics mod options)) causes a variety of different issues with shaders.

Sometimes it's the whole screen going black (Complementary V4), or the whole screen being red with a massive cyan semicircle taking over the top half of the screen (FastPBR), sometimes the game seems to render no actual shader but instead uses normal maps instead of the normal textures, meaning metal things are green, rough things are red, etc. (Complementary V4). And there's more weird things I probably forgot).

Below is a screenshot of my mods folder, so again, no idea if this is a direct incompatibility between seaborgium and iris or if something else is making this mess, but I thought I should let you know. I don't have the time to test what is going on, I tried running just sodium, iris and seaborgium (all latest versions of mods & fabric on 1.19.4) but it crashed.

![Screenshot (2018)](https://user-images.githubusercontent.com/132772089/236636301-391ca19c-ae95-4f21-8c99-403ac8d31a10.png)

Hope you have luck in figuring this out, if not I guess it's ok if no one else complains :)
